In [67]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
import warnings
warnings.filterwarnings('ignore')

In [68]:
df = pd.DataFrame()
df['year'] = np.arange(2018,2023,1)
df['place'] = np.array(['chennai','Hyderabad','punjab','Hyderabad','chennai'])
df['score'] = np.array([206,305,281,432,321])
df

year      place  score
0  2018    chennai    206
1  2019  Hyderabad    305
2  2020     punjab    281
3  2021  Hyderabad    432
4  2022    chennai    321

In [69]:
label = LabelEncoder()
df['place'] = label.fit_transform(df['place'])
df

year  place  score
0  2018      1    206
1  2019      0    305
2  2020      2    281
3  2021      0    432
4  2022      1    321

In [70]:
x = df[['year','place']]
y = df[['score']]

In [ ]:
#Linear Regression
model1 = LinearRegression()
model1.fit(x,y)

LinearRegression()

In [ ]:
# i simply done not testing and going for prediction
# Assume final match is on Chennai for the year 2023
model1.predict([[2023,1]])

array([[405.6]])

In [ ]:
#LogisticRegression
#Cash price more than five lakhs
df['Cash price more than five lakhs'] = np.array(['yes','no','no','yes','yes'])
df

year  place  score Cash price more than five lakhs
0  2018      1    206                             yes
1  2019      0    305                              no
2  2020      2    281                              no
3  2021      0    432                             yes
4  2022      1    321                             yes

In [ ]:
df['Cash price more than five lakhs'] = label.fit_transform(df['Cash price more than five lakhs'])
df

year  place  score  Cash price more than five lakhs
0  2018      1    206                                1
1  2019      0    305                                0
2  2020      2    281                                0
3  2021      0    432                                1
4  2022      1    321                                1

In [ ]:
x1 = df[['year','place','score']]
y1 = df[['Cash price more than five lakhs']]

In [ ]:
model2 = LogisticRegression()
model2.fit(x1,y1)

LogisticRegression()

In [75]:
model2.predict([[2023,1,405.6]])
# It means yes,he will win cash price more than five lakhs

array([1])

In [ ]:
#Decisiontreeregressor
model3 = DecisionTreeRegressor()
model3.fit(x,y)

DecisionTreeRegressor()

In [ ]:
# i simply done not testing and going for prediction
# Assume final match is on Chennai for the year 2023
model3.predict([[2023,1]])
# See the changes,the result is last record result because attributes and records are less (no sufficient data)

array([321.])

In [71]:
#Support vector Regression
model4 = SVR()
model4.fit(x,y)

SVR()

In [74]:
# i simply done not testing and going for prediction
# Assume final match is on Chennai for the year 2023
model4.predict([[2023,1]])
# Note it the result is changing from LinearRegression

array([305.00001768])